import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const skillsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'skills',
  parts: [
    { id: 'root' }, { id: 'header' },
    { id: 'content' }, { id: 'installed' }, { id: 'sidebar' }, { id: 'sidebarHeader' },
    { id: 'sidebarTitle' }, { id: 'sidebarSearch' }, { id: 'sidebarNav' }, { id: 'sidebarItem' },
    { id: 'sidebarItemIcon' }, { id: 'sidebarItemLabel' }, { id: 'sidebarItemCount' },
    { id: 'main' }, { id: 'toolbar' },
    { id: 'filterAction' },
    { id: 'installedTable' }, { id: 'installedListHeader' }, { id: 'installedListTitle' }, { id: 'installedListCount' },
    { id: 'loading' }, { id: 'error' }, { id: 'empty' }, { id: 'list' }, { id: 'skeleton' },
    { id: 'installedCard' }, { id: 'installedCardOpen' }, { id: 'installedCardTop' }, { id: 'installedCardIcon' },
    { id: 'installedCardInfo' }, { id: 'installedCardName' }, { id: 'installedCardDescription' },
    { id: 'installedCardMeta' }, { id: 'installedCardSource' }, { id: 'installedCardLevel' },
    { id: 'installedCardStatus' }, { id: 'installedCardActions' }, { id: 'installedCardDetails' },
    { id: 'installedCardDelete' },
    { id: 'pagination' }, { id: 'pageButton' }, { id: 'pageInfo' },
    { id: 'discover' }, { id: 'discoverHero' }, { id: 'discoverHeroContent' },
    { id: 'discoverTitle' }, { id: 'discoverSubtitle' },
    { id: 'resultsInfo' },
    { id: 'detail' }, { id: 'detailBadges' }, { id: 'detailDescriptionViewport' },
    { id: 'detailDescription' }, { id: 'detailMetadata' },
    { id: 'groups' }, { id: 'groupsHeader' }, { id: 'groupList' },
    { id: 'groupTable' }, { id: 'groupListHeader' },
    { id: 'groupRow' }, { id: 'groupOpen' }, { id: 'groupActions' },
    { id: 'groupEditor' }, { id: 'groupMembers' }, { id: 'groupMember' },
  ],
  facets: [
    { id: 'tab', attribute: 'data-openbitfun-tab', values: ['installed', 'discover'] },
    { id: 'category', attribute: 'data-openbitfun-category', values: ['all', 'builtin', 'user', 'project', 'groups'] },
    { id: 'level', attribute: 'data-openbitfun-level', values: ['user', 'project'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'focusVisible', selector: { kind: 'self', suffix: ':focus-visible' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-openbitfun-state~="active"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-openbitfun-state~="empty"]' } },
    { id: 'shadowed', selector: { kind: 'self', suffix: '[data-openbitfun-state~="shadowed"]' } },
    { id: 'builtin', selector: { kind: 'self', suffix: '[data-openbitfun-state~="builtin"]' } },
    { id: 'enabled', selector: { kind: 'self', suffix: '[data-openbitfun-state~="enabled"]' } },
    { id: 'dirty', selector: { kind: 'self', suffix: '[data-openbitfun-state~="dirty"]' } },
    { id: 'covered', selector: { kind: 'self', suffix: '[data-openbitfun-state~="covered"]' } },
  ],
};
