const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
function load(name,deps={}){const source=fs.readFileSync(path.join(__dirname,'../../entry/src/main/ets/services',name+'.ets'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;const exported={};new Function('require','exports',js)(name=>deps[name]||{},exported);return exported;}
const {RemoteSessionManager}=load('RemoteSessionManager',{'./Encoding':{Encoding:{base64ToBytes:value=>new Uint8Array(Buffer.from(value,'base64'))}},'./RemoteResponseMapper':{RemoteResponseMapper:{basename:value=>value.split('/').at(-1)}}});
function manager(total){const value=Object.create(RemoteSessionManager.prototype);value.transportGeneration=0;value.transport={};let reads=0;value.readFileChunk=async(_path,offset,limit)=>{reads++;const count=Math.min(limit,total-offset);return {name:'large.bin',mimeType:'application/octet-stream',totalSize:total,offset,chunkSize:count,revision:'stable',contentBase64:Buffer.alloc(count,3).toString('base64')};};return {value,get reads(){return reads;}};}
test('101 MiB native download writes each bounded chunk before requesting the next',async()=>{const f=manager(101*1024*1024);let total=0,writes=0;const info=await f.value.streamFile('/remote/large','session',async bytes=>{writes++;assert.equal(f.reads,writes);assert.ok(bytes.length<=3*1024*1024);total+=bytes.length;await Promise.resolve();});assert.equal(total,101*1024*1024);assert.equal(info.size,total);assert.equal(writes,34);});
test('target switch during native sink write fails before reading another chunk',async()=>{const f=manager(8*1024*1024);await assert.rejects(f.value.streamFile('/remote/large','session',async()=>{f.value.transportGeneration++;}),/target changed/);assert.equal(f.reads,1);});
test('file revision change never reaches the native sink as a mixed second chunk',async()=>{const f=manager(8*1024*1024);const read=f.value.readFileChunk;f.value.readFileChunk=async(...args)=>{const page=await read(...args);if(page.offset)page.revision='changed';return page;};let writes=0;await assert.rejects(f.value.streamFile('/remote/large','session',async()=>{writes++;}),/changed/);assert.equal(writes,1);});
const {RemoteFileDownloadController}=load('RemoteFileDownloadController',{'../i18n/RemoteI18n':{RemoteI18n:{t:x=>x,f2:(_x,name)=>name}},'./RemoteUiState':{RemoteUiState:{normalizeRemoteFilePath:x=>x,formatBytes:String}},'./RemoteLogger':{RemoteLogger:{info(){},error(){}}},'./ConnectionErrorPolicy':{ConnectionErrorPolicy:{errorText:String}}});
test('failed native download aborts the sink and never reports a saved destination',async()=>{let abort=0,finish=0;const statuses=[];const client={async streamFile(_p,_s,write){await write(new Uint8Array([1]),{name:'x',size:2,mimeType:'x'});throw Error('changed');}};const saver={async begin(){},async write(){},async finish(){finish++;return 'x';},async abort(){abort++;}};const controller=new RemoteFileDownloadController(client,(_p,saved)=>statuses.push(saved),()=>{},()=>{},()=>{},1,{setTimeout(){return 1;},clearTimeout(){}},saver);await controller.download('/x','s',false,true);assert.equal(abort,1);assert.equal(finish,0);assert.ok(statuses.every(value=>value===''));});
test('cancel during sink IO aborts the incomplete file instead of finalizing it',async()=>{let abort=0,finish=0,controller;const client={async streamFile(_p,_s,write){await write(new Uint8Array([1]),{name:'x',size:1,mimeType:'x'});return {name:'x',size:1,mimeType:'x'};}};const saver={async begin(){},async write(){controller.cancel();},async finish(){finish++;return 'x';},async abort(){abort++;}};controller=new RemoteFileDownloadController(client,()=>{},()=>{},()=>{},()=>{},1,{setTimeout(){return 1;},clearTimeout(){}},saver);await controller.download('/x','s',false,true);assert.equal(abort,1);assert.equal(finish,0);});

test('download keeps its captured saved workspace when the runtime selection changes',async()=>{const f=manager(8*1024*1024);f.value.workspace={hasWorkspace:true,path:'/first',remoteConnectionId:'saved-1'};const read=f.value.readFileChunk;const scopes=[];f.value.readFileChunk=async(...args)=>{scopes.push(args[4]);return read(...args);};await f.value.streamFile('/remote/large',undefined,async()=>{f.value.workspace.path='/second';f.value.workspace.remoteConnectionId='saved-2';});assert.ok(scopes.length>1);for(const scope of scopes)assert.equal(scope.path,'/first'),assert.equal(scope.remoteConnectionId,'saved-1');});
test('unbound file download fails before contacting a provider',async()=>{const f=manager(1);await assert.rejects(f.value.streamFile('/x',undefined,async()=>{}),/workspace identity/);assert.equal(f.reads,0);});
