package com.openbitfun.mobile.core.transport

/**
 * Identity of THIS client build, reported to the Relay at login and on every
 * realtime (re)connect so the Relay can gate remote control between devices.
 *
 * Compatibility is decided by the Relay alone from the two stored protocol
 * numbers; clients read the Relay-computed `compatible` flag on the device
 * directory instead of re-deriving the rule. The rule the Relay applies is:
 * two devices are mutually controllable only when BOTH report a number AND the
 * numbers are equal.
 *
 * Semantics of [CLIENT_PROTOCOL_VERSION]:
 *
 *  - legacy clients: report nothing (unreported, so the Relay judges them
 *    incompatible, never "legacy-compatible");
 *  - this build: `2`;
 *  - increment only on a breaking change to the client control contract.
 *
 * Kept numerically identical to
 * `openbitfun_product_domains::account::CLIENT_PROTOCOL_VERSION` in
 * `src/crates/contracts/product-domains/src/account.rs` and to
 * `src/shared/relay-transport/ClientBuild.ts`; `ClientBuildContractTest` pins
 * the three together so one side can never drift.
 */
public const val CLIENT_PROTOCOL_VERSION: Int = 2

/**
 * Product build string reported next to [CLIENT_PROTOCOL_VERSION] for
 * diagnostics only; the Relay gates control on the protocol number, never on
 * this string. [WORKSPACE_PACKAGE_VERSION] is generated by
 * `:core-transport:generateClientBuild` from the workspace `package.json` — the
 * release version release-please bumps together with `Cargo.toml` — so it is a
 * single source shared with web-ui and mobile-web and never a hand-maintained
 * literal.
 */
public const val CLIENT_VERSION: String = WORKSPACE_PACKAGE_VERSION
