import type { ComponentMeta } from "../../registry.types";

export const selectMeta = {
  category: "form",
  description: "A select-only combobox whose expanded header and grouped options share one themed surface, with typed values, native form participation, and keyboard navigation.",
  maturity: "stable",
  name: "Select",
  props: [
    { name: "options", type: "readonly SelectOption[] (supports option-level testId and data-* attributes)" },
    { name: "value", type: "SelectValue" },
    { name: "defaultValue", type: "SelectValue" },
    { name: "placeholder", type: "string" },
    { name: "leading", type: "ReactNode" },
    { defaultValue: "md", name: "size", type: "sm | md | lg" },
    { defaultValue: "bottom", name: "placement", type: "top | bottom" },
    { name: "open / defaultOpen", type: "boolean" },
    { name: "onOpenChange", type: "(open: boolean) => void" },
    { defaultValue: "false", name: "invalid", type: "boolean" },
    { name: "onValueChange", type: "(value: SelectValue) => void" },
  ],
  states: ["default", "hover", "focus-visible", "open", "invalid", "disabled"],
  tokens: [
    "color.field.background",
    "color.field.placeholder",
    "opacity.iconArtwork",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.control.highlight.background",
    "color.selection.surface",
    "color.surface.panel",
    "color.border.subtle",
    "color.action.neutral.content",
    "color.action.neutral.surface",
    "color.action.neutral.surfacePressed",
    "color.status.danger.border",
    "color.status.danger.surface",
    "color.focus.ring",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.select.paddingInline",
    "control.select.leadingInset",
    "control.select.trailingInset",
    "control.select.contentGap",
    "control.select.indicatorSize",
    "control.select.radius",
    "overlay.menu.inlineSize",
    "overlay.menu.maxBlockSize",
    "overlay.menu.surfacePadding",
    "overlay.menu.surfaceRadius",
    "overlay.menu.rowGap",
    "overlay.menu.sectionGap",
    "overlay.menu.headingHeight",
    "overlay.menu.headingPaddingInline",
    "overlay.menu.itemHeight",
    "overlay.menu.itemPaddingInline",
    "overlay.menu.itemGap",
    "overlay.menu.itemRadius",
    "overlay.menu.itemIconSize",
    "shadow.menu",
    "type.label.md.fontSize",
  ],
} as const satisfies ComponentMeta;
