import type { ComponentMeta } from "../../registry.types";

export const buttonMeta = {
  category: "action",
  description: "An action with transparent outline and text variants, neutral fill, secondary, and primary presentation.",
  maturity: "stable",
  name: "Button",
  props: [
    { defaultValue: "outline", name: "variant", type: "outline | fill | secondary | primary | text" },
    { defaultValue: "md", name: "size", type: "xs | sm | md | lg" },
    { defaultValue: "neutral", name: "tone", type: "neutral | danger" },
    { defaultValue: "false", name: "loading", type: "boolean" },
    { defaultValue: "overflow", name: "labelBehavior", type: "overflow | static" },
    { name: "leadingIcon", type: "ReactNode" },
    { name: "trailingIcon", type: "ReactNode" },
  ],
  states: ["default", "hover", "active", "disabled"],
  tokens: [
    "opacity.iconArtwork",
    "component.button.content",
    "component.button.outlineBorder",
    "component.button.outlineBorderInteractive",
    "component.button.fillBackground",
    "component.button.fillBackgroundHover",
    "component.button.fillBackgroundPressed",
    "component.button.primaryBackground",
    "component.button.primaryBackgroundHover",
    "component.button.primaryBackgroundPressed",
    "component.button.primaryContentDisabled",
    "component.button.textContent",
    "component.button.textContentHover",
    "component.button.textContentDisabled",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.primary.content",
    "color.surface.tertiary",
    "color.border.default",
    "color.border.strong",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.content",
    "color.status.danger.surface",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.button.xsHeight",
    "control.button.xsPaddingInline",
    "control.button.xsLeadingIconSize",
    "control.button.xsTrailingIconSize",
    "type.meta.fontSize",
    "type.label.sm.fontSize",
    "type.label.md.fontSize",
    "type.label.lg.fontSize",
    "type.label.selected.fontWeight",
    "radius.pill",
  ],
} as const satisfies ComponentMeta;
