import type { ComponentMeta } from "../../registry.types";

export const segmentedControlMeta = {
  category: "form",
  description: "A compact pill-shaped single-choice control that switches between a small set of exclusive modes.",
  maturity: "stable",
  name: "SegmentedControl",
  props: [
    { name: "interaction", type: "radio | buttons", defaultValue: "radio" },
    { name: "labelBehavior", type: "overflow | static", defaultValue: "overflow" },
    { name: "options", type: "readonly SegmentedControlOption[]" },
    { name: "value", type: "string" },
    { name: "defaultValue", type: "string" },
    { name: "onValueChange", type: "(value: string) => void" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
    { defaultValue: '"content"', name: "distribution", type: '"content" | "fill"' },
    { defaultValue: '"sm"', name: "size", type: '"sm" | "md"' },
    { defaultValue: '"accent"', name: "tone", type: '"accent" | "neutral"' },
    { defaultValue: '"bar"', name: "variant", type: '"bar" | "pills"' },
  ],
  states: ["selected", "unselected", "hover", "active", "disabled"],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "space.3",
    "color.content.primary",
    "color.focus.ring",
    "color.surface.raised",
    "color.surface.subtle",
    "control.segmentedControl.gap",
    "control.segmentedControl.padding",
    "control.segmentedControl.paddingMd",
    "control.segmentedControl.radius",
    "control.segmentedControl.segmentHeight",
    "control.segmentedControl.segmentHeightMd",
    "control.segmentedControl.pillSegmentHeight",
    "control.segmentedControl.segmentPaddingInline",
    "control.segmentedControl.segmentPaddingInlineMd",
    "control.segmentedControl.segmentGap",
    "control.segmentedControl.segmentRadius",
    "control.segmentedControl.pillSegmentRadius",
    "control.segmentedControl.iconSize",
    "control.segmentedControl.iconSizeMd",
    "control.height.md",
    "radius.pill",
    "space.4",
    "type.label.md.fontSize",
    "type.label.selected.fontWeight",
  ],
} as const satisfies ComponentMeta;
