import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const reviewPlatformAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'review-platform',
  componentAttribute: 'data-openbitfun-product-component',
  parts: [
    { id: 'root' },
    { id: 'chrome' },
    { id: 'actions' },
    { id: 'body' },
    { id: 'listPane' },
    { id: 'listToolbar' },
    { id: 'filters' },
    { id: 'listScroll' },
    { id: 'listItem' },
    { id: 'listItemMain' },
    { id: 'listItemTitle' },
    { id: 'listItemMeta' },
    { id: 'pagination' },
    { id: 'emptyState' },
    { id: 'errorState' },
    { id: 'loadingState' },
    { id: 'authGate' },
    { id: 'authCopy' },
    { id: 'authActions' },
    { id: 'detailPane' },
    { id: 'detailHeader' },
    { id: 'detailTitle' },
    { id: 'detailState' },
    { id: 'detailMeta' },
    { id: 'detailActions' },
    { id: 'facts' },
    { id: 'tabs' },
    { id: 'tabBar' },
    { id: 'tabContent' },
    { id: 'section' },
    { id: 'ciItem' },
    { id: 'ciHead' },
    { id: 'ciStatus' },
    { id: 'ciLog' },
    { id: 'thread' },
    { id: 'threadHead' },
    { id: 'threadBody' },
    { id: 'fileList' },
    { id: 'fileCard' },
    { id: 'fileRow' },
    { id: 'fileStatus' },
    { id: 'fileDelta' },
    { id: 'diff' },
  ],
  facets: [
    { id: 'layout', attribute: 'data-openbitfun-layout', values: ['full', 'detail'] },
    { id: 'view', attribute: 'data-openbitfun-view', values: ['list', 'detail'] },
  ],
  states: [
    { id: 'selected', selector: { kind: 'self', suffix: '[data-openbitfun-state~="selected"]' } },
  ],
};
