/**
 * Pending queue module
 *
 * Legacy/fallback frontend queue and explicit recovery drafts. Native hosts
 * advertising dialog_queue_v1 use HostDialogQueue for new submissions.
 *
 * This frontend queue is used while a session's current dialog turn is
 * still running. Items are kept here (NOT submitted to the backend scheduler)
 * until the session returns to IDLE, at which point the head item is drained
 * via the regular `sendMessage` path. Users may also pop an item early through
 * the "send now" action which triggers `agentAPI.steerDialogTurn`, injecting
 * the message mid-turn.
 *
 * State is persisted per device surface and session so the queue survives a
 * page refresh without letting equal session ids on two devices collide.
 */

import { createLogger } from '@/shared/utils/logger';
import type { DialogTurn, QueuedComposerDraft, QueuedMessage } from '../../types/flow-chat';
import {
  getActiveSurfaceId,
  onSurfaceActivated,
  surfaceScopedKey,
  type DeviceSurfaceId,
} from '@/infrastructure/peer-device/deviceSurface';

const log = createLogger('PendingQueueModule');

const STORAGE_PREFIX = 'openbitfun.flowChat.pendingQueue.v1.';
const MAX_QUEUE_DEPTH = 20;

const LIVE_TURN_STATUSES = new Set<DialogTurn['status']>([
  'pending',
  'image_analyzing',
  'processing',
  'finishing',
]);

function normalizeQueueText(value: string | undefined): string {
  return value?.trim() ?? '';
}

export function queuedItemDuplicatesLiveTurn(
  item: Pick<QueuedMessage, 'content' | 'displayMessage' | 'localDialogTurnId'>,
  turns: Array<Pick<DialogTurn, 'id' | 'status' | 'userMessage'>>,
): boolean {
  const itemTexts = [item.displayMessage, item.content]
    .map(normalizeQueueText)
    .filter(text => text.length > 0);
  return turns.some(turn => {
    if (!LIVE_TURN_STATUSES.has(turn.status)) {
      return false;
    }
    if (item.localDialogTurnId && item.localDialogTurnId === turn.id) {
      return true;
    }
    const turnText = normalizeQueueText(turn.userMessage?.content);
    return Boolean(turnText && itemTexts.includes(turnText));
  });
}

export interface EnqueueInput {
  sessionId: string;
  content: string;
  displayMessage?: string;
  agentType?: string;
  imageContexts?: unknown[];
  imageDisplayData?: unknown[];
  composerDraft?: QueuedComposerDraft;
  userMessageMetadata?: Record<string, unknown>;
  /**
   * How many times this content has already been auto-restored from a failed
   * dialog turn. Items with `retryCount > 0` are treated as "failed-recovery"
   * entries: the auto-drain listener will skip them so the user must explicitly
   * confirm (edit / send now / delete). Defaults to 0.
   */
  retryCount?: number;
  /**
   * Initial item status. Used by the failed-recovery path to mark an item as
   * `'failed'` from the start so the UI shows the correct visual.
   */
  initialStatus?: QueuedMessage['status'];
}

export type PendingQueueListener = (sessionId: string, items: QueuedMessage[]) => void;
export type QueuedMessagePayloadUpdate = Pick<QueuedMessage, 'content' | 'displayMessage' | 'composerDraft' | 'userMessageMetadata'>;

class PendingQueueManager {
  private static _instance: PendingQueueManager | null = null;
  private queues = new Map<string, QueuedMessage[]>();
  private listeners = new Set<PendingQueueListener>();
  private hydrated = false;
  private lastSurfaceId = getActiveSurfaceId();

  static getInstance(): PendingQueueManager {
    if (!PendingQueueManager._instance) {
      PendingQueueManager._instance = new PendingQueueManager();
    }
    return PendingQueueManager._instance;
  }

  private constructor() {
    this.hydrateFromStorage();
    onSurfaceActivated((scope) => {
      const previousSurfaceId = this.lastSurfaceId;
      this.lastSurfaceId = scope.surfaceId;
      const affectedSessionIds = new Set([
        ...this.sessionIdsForSurface(previousSurfaceId),
        ...this.sessionIdsForSurface(scope.surfaceId),
      ]);
      // A component may keep the same session id across two device surfaces.
      // Notify the union so it replaces A's queue with B's queue (or empty).
      for (const sessionId of affectedSessionIds) {
        this.notify(sessionId);
      }
    });
  }

  private queueKey(sessionId: string, surfaceId = getActiveSurfaceId()): string {
    return surfaceScopedKey(surfaceId, sessionId);
  }

  private storageKey(sessionId: string, surfaceId: DeviceSurfaceId): string {
    return STORAGE_PREFIX + encodeURIComponent(JSON.stringify([surfaceId, sessionId]));
  }

  private sessionIdsForSurface(surfaceId: DeviceSurfaceId): string[] {
    const sessionIds: string[] = [];
    for (const key of this.queues.keys()) {
      try {
        const [ownedSurfaceId, sessionId] = JSON.parse(key) as [string, string];
        if (ownedSurfaceId === surfaceId) {
          sessionIds.push(sessionId);
        }
      } catch {
        // Internal keys are always generated by surfaceScopedKey. Ignore a
        // malformed entry rather than making a surface switch fail.
      }
    }
    return sessionIds;
  }

  /** Lazily load all per-session queues from localStorage on first construction. */
  private hydrateFromStorage(): void {
    if (this.hydrated) return;
    this.hydrated = true;
    if (typeof window === 'undefined' || !window.localStorage) return;
    try {
      for (let i = 0; i < window.localStorage.length; i++) {
        const key = window.localStorage.key(i);
        if (!key || !key.startsWith(STORAGE_PREFIX)) {
          continue;
        }
        const encoded = key.slice(STORAGE_PREFIX.length);
        let surfaceId: DeviceSurfaceId;
        let sessionId: string;
        try {
          [surfaceId, sessionId] = JSON.parse(decodeURIComponent(encoded)) as [string, string];
          if (!surfaceId || !sessionId) {
            continue;
          }
        } catch {
          continue;
        }
        const raw = window.localStorage.getItem(key);
        if (!raw) continue;
        try {
          const parsed = JSON.parse(raw) as QueuedMessage[];
          if (Array.isArray(parsed) && parsed.length > 0) {
            this.queues.set(this.queueKey(sessionId, surfaceId), parsed);
          }
        } catch (err) {
          log.warn('Failed to parse persisted queue, dropping', { sessionId, err });
          window.localStorage.removeItem(key);
        }
      }
    } catch (err) {
      log.warn('Queue hydration failed', err);
    }
  }

  private persist(sessionId: string, surfaceId = getActiveSurfaceId()): void {
    if (typeof window === 'undefined' || !window.localStorage) return;
    const items = this.queues.get(this.queueKey(sessionId, surfaceId));
    const key = this.storageKey(sessionId, surfaceId);
    try {
      if (!items || items.length === 0) {
        window.localStorage.removeItem(key);
      } else {
        window.localStorage.setItem(key, JSON.stringify(items));
      }
    } catch (err) {
      log.warn('Queue persistence failed', { sessionId, err });
    }
  }

  list(sessionId: string): QueuedMessage[] {
    return this.listForSurface(getActiveSurfaceId(), sessionId);
  }

  listForSurface(surfaceId: DeviceSurfaceId, sessionId: string): QueuedMessage[] {
    return this.queues.get(this.queueKey(sessionId, surfaceId)) ?? [];
  }

  isFull(sessionId: string): boolean {
    return this.list(sessionId).length >= MAX_QUEUE_DEPTH;
  }

  enqueue(input: EnqueueInput): QueuedMessage {
    return this.enqueueForSurface(getActiveSurfaceId(), input);
  }

  enqueueForSurface(surfaceId: DeviceSurfaceId, input: EnqueueInput): QueuedMessage {
    const key = this.queueKey(input.sessionId, surfaceId);
    const items = this.queues.get(key) ?? [];
    if (items.length >= MAX_QUEUE_DEPTH) {
      throw new Error(`Pending queue is full (max ${MAX_QUEUE_DEPTH})`);
    }
    const item: QueuedMessage = {
      id: `pending_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      sessionId: input.sessionId,
      content: input.content,
      displayMessage: input.displayMessage,
      timestamp: Date.now(),
      status: input.initialStatus ?? 'queued',
      retryCount: input.retryCount ?? 0,
      agentType: input.agentType,
      imageContexts: input.imageContexts,
      imageDisplayData: input.imageDisplayData,
      composerDraft: input.composerDraft
        ? {
            value: input.composerDraft.value,
            contexts: [...input.composerDraft.contexts],
            pendingLargePastes: { ...input.composerDraft.pendingLargePastes },
          }
        : undefined,
      userMessageMetadata: input.userMessageMetadata,
    };
    items.push(item);
    this.queues.set(key, items);
    this.persist(input.sessionId, surfaceId);
    this.notifySurface(surfaceId, input.sessionId);
    return item;
  }

  /**
   * Drop queue items that are the same user message as a turn this surface
   * is already projecting as live. A device switch must not keep a duplicate
   * "pending send" of a turn the host is executing.
   */
  reconcileAgainstLiveTurns(
    sessionId: string,
    turns: Array<Pick<DialogTurn, 'id' | 'status' | 'userMessage'>>,
    surfaceId = getActiveSurfaceId(),
  ): number {
    const key = this.queueKey(sessionId, surfaceId);
    const items = this.queues.get(key);
    if (!items || items.length === 0) {
      return 0;
    }
    const next = items.filter(item => !queuedItemDuplicatesLiveTurn(item, turns));
    const removed = items.length - next.length;
    if (removed === 0) {
      return 0;
    }
    if (next.length === 0) {
      this.queues.delete(key);
    } else {
      this.queues.set(key, next);
    }
    this.persist(sessionId, surfaceId);
    this.notifySurface(surfaceId, sessionId);
    return removed;
  }

  remove(sessionId: string, id: string): boolean {
    const surfaceId = getActiveSurfaceId();
    const key = this.queueKey(sessionId, surfaceId);
    const items = this.queues.get(key);
    if (!items) return false;
    const next = items.filter(item => item.id !== id);
    if (next.length === items.length) return false;
    if (next.length === 0) {
      this.queues.delete(key);
    } else {
      this.queues.set(key, next);
    }
    this.persist(sessionId);
    this.notify(sessionId);
    return true;
  }

  /** Confirm a queued item for immediate idle-session drain without rebuilding its payload. */
  promoteForExplicitDrain(sessionId: string, id: string): boolean {
    const items = this.queues.get(this.queueKey(sessionId));
    if (!items) return false;
    const index = items.findIndex(item => item.id === id);
    if (index === -1) return false;
    const item = items[index];
    if (index > 0) {
      items.splice(index, 1);
      items.unshift(item);
    }
    item.status = 'queued';
    item.retryCount = 0;
    this.persist(sessionId);
    this.notify(sessionId);
    return true;
  }

  setStatus(sessionId: string, id: string, status: QueuedMessage['status']): void {
    const items = this.queues.get(this.queueKey(sessionId));
    if (!items) return;
    const idx = items.findIndex(item => item.id === id);
    if (idx === -1) return;
    items[idx] = { ...items[idx], status };
    this.persist(sessionId);
    this.notify(sessionId);
  }

  /** Update a still-pending payload atomically without changing FIFO identity or attachments. */
  updatePayloadForSurface(
    surfaceId: DeviceSurfaceId,
    sessionId: string,
    id: string,
    update: (current: QueuedMessage) => QueuedMessagePayloadUpdate | null,
  ): boolean {
    const key = this.queueKey(sessionId, surfaceId);
    const items = this.queues.get(key);
    const index = items?.findIndex(item => item.id === id) ?? -1;
    if (!items || index < 0 || !['queued', 'failed'].includes(items[index].status)) return false;
    const payload = update(items[index]);
    if (!payload) return false;
    this.queues.set(key, items.map((item, i) => i === index ? { ...item, ...payload } : item));
    this.persist(sessionId, surfaceId);
    this.notifySurface(surfaceId, sessionId);
    return true;
  }

  /** Pop and return the head item (FIFO). */
  consumeNext(sessionId: string): QueuedMessage | undefined {
    const surfaceId = getActiveSurfaceId();
    const key = this.queueKey(sessionId, surfaceId);
    const items = this.queues.get(key);
    if (!items || items.length === 0) return undefined;
    const [head, ...rest] = items;
    if (rest.length === 0) {
      this.queues.delete(key);
    } else {
      this.queues.set(key, rest);
    }
    this.persist(sessionId);
    this.notify(sessionId);
    return head;
  }

  clear(sessionId: string): void {
    const surfaceId = getActiveSurfaceId();
    const key = this.queueKey(sessionId, surfaceId);
    if (!this.queues.has(key)) return;
    this.queues.delete(key);
    this.persist(sessionId);
    this.notify(sessionId);
  }

  /** Permanently discard every queued message owned by one detached peer. */
  clearSurface(surfaceId: DeviceSurfaceId): void {
    const sessionIds = this.sessionIdsForSurface(surfaceId);
    for (const sessionId of sessionIds) {
      this.queues.delete(this.queueKey(sessionId, surfaceId));
      this.persist(sessionId, surfaceId);
      this.notifySurface(surfaceId, sessionId);
    }
  }

  subscribe(listener: PendingQueueListener): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notify(sessionId: string): void {
    const snapshot = this.list(sessionId).slice();
    this.listeners.forEach(listener => {
      try {
        listener(sessionId, snapshot);
      } catch (err) {
        log.error('Pending queue listener error', { sessionId, err });
      }
    });
  }

  private notifySurface(surfaceId: DeviceSurfaceId, sessionId: string): void {
    if (surfaceId === getActiveSurfaceId()) {
      this.notify(sessionId);
    }
  }
}

export const pendingQueueManager = PendingQueueManager.getInstance();
