import type { ComponentMeta } from "../../registry.types";

export const menuMeta = {
  category: "navigation",
  description: "Grouped menu anatomy plus anchored MenuPopover with nested keyboard navigation, pointer corridors and focus return.",
  maturity: "stable",
  name: "Menu",
  props: [
    { name: "children", type: "ReactNode" },
    { name: "MenuList.children", type: "ReactNode (row stack inside custom scroll or animation wrappers)" },
    { defaultValue: "false", name: "autoFocusFirstItem", type: "boolean" },
    { defaultValue: "auto", name: "scrollbarVisibility", type: "auto | always | hidden" },
    { defaultValue: "fixed", name: "inlineSize", type: "fixed | content" },
    { name: "MenuPopover.items", type: "readonly MenuEntry[]" },
    { name: "MenuPopover.open / onClose", type: "boolean / () => void" },
    { name: "MenuPopover.anchorRef / position", type: "RefObject<HTMLElement> / { x: number; y: number }" },
    { name: "MenuPopover.placement", type: "top | bottom | left | right", defaultValue: "bottom" },
    { name: "MenuPopover.portalContainer", type: "Element | DocumentFragment | (() => Element | null)" },
  ],
  states: ["default", "scrolling", "focus-within", "disabled-item", "checked-item"],
  tokens: [
    "color.surface.panel",
    "color.border.subtle",
    "color.content.muted",
    "color.content.caption",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfaceHover",
    "color.selection.surface",
    "color.focus.ring",
    "overlay.menu.inlineSize",
    "overlay.menu.minInlineSize",
    "overlay.menu.maxBlockSize",
    "overlay.menu.surfacePadding",
    "overlay.menu.surfaceRadius",
    "overlay.menu.rowGap",
    "overlay.menu.sectionGap",
    "overlay.menu.headingHeight",
    "overlay.menu.headingPaddingInline",
    "overlay.menu.headingGap",
    "type.meta.fontSize",
    "overlay.menu.headingActionSize",
    "overlay.menu.itemHeight",
    "overlay.menu.itemPaddingInline",
    "overlay.menu.itemGap",
    "overlay.menu.itemRadius",
    "overlay.menu.itemIconSize",
    "overlay.menu.scrollbarGap",
    "scrollbar.width",
    "scrollbar.radius",
    "shadow.menu",
  ],
} as const satisfies ComponentMeta;
