import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const externalSourcesConfigAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'external-sources-config',
  componentAttribute: 'data-openbitfun-product-component',
  parts: [
    { id: 'root' },
    { id: 'hostMode' },
    { id: 'notice' },
    { id: 'policyCard' },
    { id: 'policySummary' },
    { id: 'policyRecovery' },
    { id: 'policyActions' },
    { id: 'diagnostics' },
    { id: 'sourceGroup' },
    { id: 'sourceDescription' },
    { id: 'sourceMembers' },
    { id: 'sourceControl' },
    { id: 'state' },
    { id: 'toolCard' },
    { id: 'toolTitle' },
    { id: 'toolDetail' },
    { id: 'toolWarning' },
    { id: 'toolActions' },
    { id: 'conflict' },
    { id: 'conflictTitle' },
    { id: 'conflictOptions' },
    { id: 'candidate' },
    { id: 'candidateState' },
    { id: 'candidateDetail' },
    { id: 'conflictHint' },
    { id: 'empty' },
    { id: 'ecosystemCard' },
    { id: 'ecosystemHeading' },
    { id: 'ecosystemName' },
    { id: 'ecosystemState' },
    { id: 'application' },
    { id: 'appAttention' },
    { id: 'applicationToggle' },
  ],
};
