import type { ComponentMeta } from "../../registry.types";

export const disclosureMeta = {
  category: "primitive",
  description: "Reveals supporting content with controlled or uncontrolled state, accessible relationships, and independent header actions.",
  maturity: "stable",
  name: "Disclosure",
  props: [
    { name: "renderHeader", type: "(triggerProps: DisclosureTriggerProps) => ReactNode" },
    { name: "contentClassName", type: "string" },
    { name: "contentInnerClassName", type: "string" },
    { name: "unmountOnClose", type: "boolean", defaultValue: "false" },
    { name: "exitDurationMs", type: "number", defaultValue: "180" },
    { name: "presentation", type: "custom | native", defaultValue: "custom" },
    { name: "summary", type: "ReactNode" },
    { name: "children", type: "ReactNode" },
    { name: "leading", type: "ReactNode" },
    { name: "description", type: "ReactNode" },
    { name: "actions", type: "ReactNode" },
    { name: "open", type: "boolean" },
    { defaultValue: "false", name: "defaultOpen", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
    { name: "onOpenChange", type: "(open: boolean) => void" },
    { name: "onToggle", type: "ToggleEventHandler<HTMLDetailsElement> (native only)" },
  ],
  states: ["closed", "open", "hover", "focus-visible", "disabled"],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfacePressed",
    "color.content.muted",
    "color.focus.ring",
    "type.label.md.fontSize",
    "type.body.sm.lineHeight",
    "type.support.fontSize",
    "layout.disclosure.triggerMinBlockSize",
    "layout.disclosure.triggerPaddingBlock",
    "layout.disclosure.triggerPaddingInline",
    "layout.disclosure.triggerGap",
    "layout.disclosure.triggerRadius",
    "layout.disclosure.indicatorSize",
    "layout.disclosure.actionsGap",
    "layout.disclosure.contentPaddingBlock",
    "layout.disclosure.contentPaddingInline",
    "space.1",
  ],
} as const satisfies ComponentMeta;
