import type { ComponentMeta } from "../../registry.types";

export const cardMeta = {
  category: "primitive",
  description: "A composable content surface with independent media, header, body, footer, spacing, clipping, and elevation contracts.",
  maturity: "stable",
  name: "Card",
  props: [
    { defaultValue: "subtle", name: "appearance", type: "raised | subtle | neutral" },
    { defaultValue: "none", name: "padding", type: "none | sm | md" },
    { defaultValue: "none", name: "gap", type: "none | sm | md | lg" },
    { defaultValue: "md", name: "radius", type: "none | sm | md | lg" },
    { defaultValue: "false", name: "clip", type: "boolean" },
    { defaultValue: "start", name: "CardHeader.contentAlign", type: "start | center | end" },
    { defaultValue: "stretch", name: "CardBody.align", type: "start | center | end | stretch" },
    { name: "children", type: "ReactNode" },
  ],
  states: ["raised", "subtle", "media"],
  tokens: [
    "color.surface.raised",
    "color.surface.subtle",
    "color.surface.canvas",
    "color.action.neutral.surface",
    "color.content.primary",
    "color.content.secondary",
    "color.border.subtle",
    "shadow.overlay",
    "layout.card.paddingSm",
    "layout.card.paddingMd",
    "layout.card.gapSm",
    "layout.card.gapMd",
    "layout.card.gapLg",
    "layout.card.radiusSm",
    "layout.card.radiusMd",
    "layout.card.radiusLg",
    "layout.card.headerGap",
    "layout.card.titleDescriptionGap",
    "layout.card.footerGap",
    "layout.card.mediaMinBlockSize",
    "type.heading.card.fontSize",
    "type.body.sm.fontSize",
  ],
} as const satisfies ComponentMeta;
