import type { ComponentMeta } from "../../registry.types";

export const actionCardMeta = {
  category: "action",
  description: "An actionable card with independent leading, title, description, selection, and sibling action areas.",
  maturity: "stable",
  name: "ActionCard",
  props: [
    { name: "body", type: "ReactNode" },
    { name: "triggerClassName", type: "string" },
    { name: "children", type: "ReactNode" },
    { name: "description", type: "ReactNode" },
    { name: "leading", type: "ReactNode" },
    { defaultValue: "[]", name: "actions", type: "readonly ActionCardAction[]" },
    { defaultValue: "sm", name: "size", type: "sm | md" },
    { defaultValue: "false", name: "selected", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
  ],
  states: ["default", "hover", "active", "focus-visible", "selected", "disabled"],
  tokens: [
    "color.actionCard.background",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.content.primary",
    "color.content.secondary",
    "color.border.default",
    "color.focus.ring",
    "control.actionCard.smMinBlockSize",
    "control.actionCard.mdMinBlockSize",
    "control.actionCard.paddingBlock",
    "control.actionCard.paddingInline",
    "control.actionCard.gap",
    "control.actionCard.leadingSize",
    "control.actionCard.iconSize",
    "control.actionCard.contentGap",
    "control.actionCard.actionsGap",
    "control.actionCard.actionsPaddingInlineEnd",
    "control.actionCard.radius",
    "type.heading.section.fontSize",
    "type.body.sm.fontSize",
    "type.actionRow.lineHeight",
  ],
} as const satisfies ComponentMeta;
