import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const updateAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'update',
  parts: [
    { id: 'notice', visualRole: 'content' },
    { id: 'noticeTitle', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'releaseArtwork', propertyProfile: 'paint', visualRole: 'decoration' },
    { id: 'indicator', propertyProfile: 'paint', visualRole: 'decoration' },
    { id: 'downloadControl', visualRole: 'content' },
    { id: 'downloadVessel', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'downloadFill', propertyProfile: 'paint', visualRole: 'decoration' },
    { id: 'downloadTransfer', propertyProfile: 'paint', visualRole: 'decoration' },
    { id: 'panel', visualRole: 'content' },
    { id: 'panelStatus', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'availableRoot' },
    { id: 'lead' },
    { id: 'leadIcon' },
    { id: 'subtitle' },
    { id: 'versions' },
    { id: 'versionRow' },
    { id: 'versionLabel' },
    { id: 'versionValue' },
    { id: 'notes' },
    { id: 'notesLabel' },
    { id: 'notesBody' },
    { id: 'actions' },
    { id: 'progressRoot' },
    { id: 'alert' },
    { id: 'progressBar' },
    { id: 'progressFill' },
    { id: 'progressHint' },
    { id: 'restartHint' },
  ],
  facets: [
    { id: 'variant', attribute: 'data-openbitfun-variant', values: ['daily', 'manual'] },
    { id: 'status', attribute: 'data-openbitfun-status', values: ['downloading', 'error', 'installed'] },
  ],
  states: [
    { id: 'highlight', selector: { kind: 'self', suffix: '[data-openbitfun-state~="highlight"]' } },
    { id: 'indeterminate', selector: { kind: 'self', suffix: '[data-openbitfun-state~="indeterminate"]' } },
  ],
};
